//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/nukleros/operator-builder-tools/pkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMLogForwarder) DeepCopyInto(out *OCMLogForwarder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMLogForwarder.
func (in *OCMLogForwarder) DeepCopy() *OCMLogForwarder {
	if in == nil {
		return nil
	}
	out := new(OCMLogForwarder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCMLogForwarder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMLogForwarderList) DeepCopyInto(out *OCMLogForwarderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCMLogForwarder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMLogForwarderList.
func (in *OCMLogForwarderList) DeepCopy() *OCMLogForwarderList {
	if in == nil {
		return nil
	}
	out := new(OCMLogForwarderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCMLogForwarderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMLogForwarderSpec) DeepCopyInto(out *OCMLogForwarderSpec) {
	*out = *in
	out.Ocm = in.Ocm
	out.Backend = in.Backend
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMLogForwarderSpec.
func (in *OCMLogForwarderSpec) DeepCopy() *OCMLogForwarderSpec {
	if in == nil {
		return nil
	}
	out := new(OCMLogForwarderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMLogForwarderSpecBackend) DeepCopyInto(out *OCMLogForwarderSpecBackend) {
	*out = *in
	out.Elasticsearch = in.Elasticsearch
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMLogForwarderSpecBackend.
func (in *OCMLogForwarderSpecBackend) DeepCopy() *OCMLogForwarderSpecBackend {
	if in == nil {
		return nil
	}
	out := new(OCMLogForwarderSpecBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMLogForwarderSpecBackendElasticsearch) DeepCopyInto(out *OCMLogForwarderSpecBackendElasticsearch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMLogForwarderSpecBackendElasticsearch.
func (in *OCMLogForwarderSpecBackendElasticsearch) DeepCopy() *OCMLogForwarderSpecBackendElasticsearch {
	if in == nil {
		return nil
	}
	out := new(OCMLogForwarderSpecBackendElasticsearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMLogForwarderSpecOcm) DeepCopyInto(out *OCMLogForwarderSpecOcm) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMLogForwarderSpecOcm.
func (in *OCMLogForwarderSpecOcm) DeepCopy() *OCMLogForwarderSpecOcm {
	if in == nil {
		return nil
	}
	out := new(OCMLogForwarderSpecOcm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMLogForwarderStatus) DeepCopyInto(out *OCMLogForwarderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*status.PhaseCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.PhaseCondition)
				**out = **in
			}
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*status.ChildResource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.ChildResource)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMLogForwarderStatus.
func (in *OCMLogForwarderStatus) DeepCopy() *OCMLogForwarderStatus {
	if in == nil {
		return nil
	}
	out := new(OCMLogForwarderStatus)
	in.DeepCopyInto(out)
	return out
}
