# permissions for end users to edit ocmlogforwarderconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ocmlogforwarderconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocm-log-forwarder-operator
    app.kubernetes.io/part-of: ocm-log-forwarder-operator
    app.kubernetes.io/managed-by: kustomize
  name: ocmlogforwarderconfig-editor-role
rules:
- apiGroups:
  - apps.dustinscott.io
  resources:
  - ocmlogforwarderconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dustinscott.io
  resources:
  - ocmlogforwarderconfigs/status
  verbs:
  - get
