apiVersion: apps.dustinscott.io/v1alpha1
kind: OCMLogForwarder
metadata:
  name: ocmlogforwarder-sample
  namespace: default
spec:
  ocm:
    secretRef: "ocm-token"
    clusterId: "22tgckqk9c2ff3jd8ve62p0i2st14vrq"
    pollInternalMinutes: 5
  backend:
    elasticSearch:
      secretRef: "elastic-auth"
      url: "https://elasticsearch-es-http.elastic-system.svc.cluster.local:9200"
      authType: "basic"
      index: "ocm_service_logs"
    type: "elasticsearch"
  version: "latest"
  debug: false
