apiVersion: apps.dustinscott.io/v1alpha1
kind: OCMLogForwarder
metadata:
  name: ocmlogforwarder-sample
  namespace: ocm-log-forwarder
spec:
  #collection:
    #name: "ocmlogforwarderconfig-sample"
    #namespace: ""
  forwarderVersion: "latest"
  ocm:
    clusterId: "22u78be01ukanemc80s27t7d49jcd8r8"
    pollInternalMinutes: 5
  debug: false
