apiVersion: apps.dustinscott.io/v1alpha1
kind: OCMLogForwarder
metadata:
  name: ocmlogforwarder-sample
  namespace: default
spec:
  ocm:
    secretRef: "ocm-token"
    clusterId: "231lma7ae9t3gsudlvhhs18knrsfb98v"
    pollInternalMinutes: 1
  backend:
    elasticsearch:
      secretRef: "elastic-auth"
      url: "https://elasticsearch-es-http.elastic-system.svc.cluster.local:9200"
      authType: "basic"
      index: "ocm_service_logs"
    type: "elasticsearch"
  version: "latest"
  debug: false
