---
# +operator-builder:resource:field=backend.type,value=elasticsearch,include=true
apiVersion: apps/v1
kind: Deployment
metadata:
  # +operator-builder:field:parent=metadata.name,type="string"
  name: ocm-log-forwarder
  labels:
    # +operator-builder:field:parent=metadata.name,type="string"
    app.kubernetes.io/name: ocm-log-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      # +operator-builder:field:parent=metadata.name,type="string"
      app.kubernetes.io/name: ocm-log-forwarder
  template:
    metadata:
      labels:
        # +operator-builder:field:parent=metadata.name,type="string"
        app.kubernetes.io/name: ocm-log-forwarder
    spec:
      # +operator-builder:field:parent=metadata.name,type="string"
      serviceAccountName: ocm-log-forwarder
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        # +operator-builder:field:parent=metadata.name,type="string"
                        - ocm-log-forwarder
      containers:
        - name: forwarder
          # +operator-builder:field:name=version,type=string,default="latest",replace="unstable",description=`
          # OCM Log Forwarder version to use.  Any of the tags from the ocm-log-forwarder GitHub
          # repo are supported here.
          # `
          image: ghcr.io/scottd018/ocm-log-forwarder:unstable
          imagePullPolicy: IfNotPresent
          env:
            # NOTE: present all config options here.  Use these as environment variables 
            #       on the deployment so that changes here result in the app realizing 
            #       those changes by restarting the managed pod.
            - name: OCM_CLUSTER_ID
              # +operator-builder:field:name=ocm.clusterId,type=string,description=`
              # Cluster ID of the cluster to forward logs from.  This Cluster ID can be found in the OCM Console
              # as part of the URL when selecting the cluster.  It shows up in a form such as
              # '22tgckqk9c2ff3jd8ve62p0i2st14vrq'.
              # `
              value: 22tgckqk9c2ff3jd8ve62p0i2st14vrq
            - name: OCM_SECRET_NAME
              # +operator-builder:field:name=ocm.secretRef,type=string,default="ocm-token",description=`
              # The secret should contain the OCM JSON token obtained from OpenShift Cluster Manager.  It should 
              # have a single key/value pair with the form of clusterId=ocmTokenJson.  The clusterId
              # should match the .spec.ocm.clusterId field, while the ocmTokenJson value should be a 
              # string form of the token obtained from OCM.
              # `
              value: ocm-token
            - name: OCM_SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OCM_POLL_INTERVAL_MINUTES
              # +operator-builder:field:name=ocm.pollInternalMinutes,type=int,default=5,description=`
              # +kubebuilder:validation:Minimum=1
              # +kubebuilder:validation:Maximum=1440
              # How frequently, in minutes, the controller will poll the OpenShift Cluster Manager console for service logs.  Must 
              # be in the range of 1 minute to 1440 minutes (1 day).
              # `
              value: "1"
            - name: BACKEND_TYPE
              # +operator-builder:field:name=backend.type,type=string,default=elasticsearch,description=`
              # +kubebuilder:validation:Enum=elasticsearch
              # Backend type where logs are sent and stored.  Only 'elasticsearch' supported at this time.  Requires
              # backend.elasticsearch.url to be set.
              # `
              value: elasticsearch
            - name: BACKEND_ES_URL
              # +operator-builder:field:name=backend.elasticsearch.url,type=string,default="https://elasticsearch-es-http.elastic-system.svc.cluster.local:9200",description=`
              # URL to which to ship logs when using the 'elasticsearch' as a backend in the .spec.backend.type
              # field of this custom resource.
              # `
              value: https://elasticsearch-es-http.elastic-system.svc.cluster.local:9200
            - name: BACKEND_ES_AUTH_TYPE
              # +operator-builder:field:name=backend.elasticsearch.authType,type=string,default="basic",description=`
              # +kubebuilder:validation:Enum=basic
              # ElasticSearch authentication type to use.  Only 'basic' supported at this time.  
              # 
              # * 'basic': For 'basic' authentication, the secret from .spec.backend.elasticsearch.secretRef should contain the 
              # basic authentication information for the ElasticSearch connection containing only a single key/value pair with 
              # the key as the username and the value as the password.
              # `
              value: basic
            - name: BACKEND_ES_INDEX
              # +operator-builder:field:name=backend.elasticsearch.index,type=string,default="ocm_service_logs",description=`
              # +kubebuilder:validation:MaxLength=128
              # Index name in ElasticSearch where service logs are sent.  Index name must be 128 characters or less.
              # `
              value: ocm_service_logs
            - name: DEBUG
              # +operator-builder:field:name=debug,type=bool,default=false,description=`
              # Enable debug logging on the log forwarder.
              # `
              value: "false"
            - name: BACKEND_ES_SECRET_NAME
              # +operator-builder:field:name=backend.elasticsearch.secretRef,type=string,default="elastic-auth",description=`
              # The secret should contain the authentication information for the ElasticSearch connection.  See 
              # .spec.backend.elasticsearch.authType for more information on secret requirements.  This secret 
              # should exist in the same namespace as the OCMLogForwarder resource.
              # `
              value: elastic-auth
            - name: BACKEND_ES_SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - "ALL"
            runAsNonRoot: true
            runAsGroup: 0
            seccompProfile: 
              type: RuntimeDefault
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
