---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  # +operator-builder:field:parent=metadata.name,type="string"
  name: ocm-log-forwarder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # +operator-builder:field:parent=metadata.name,replace="ocm-log-forwarder",type="string"
  name: ocm-log-forwarder-ocm
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
    resourceNames:
      # +operator-builder:field:name=ocm.secretRef,type=string,default="ocm-token"
      - ocm-token
---
# +operator-builder:resource:field=backend.type,value=elasticsearch,include=true
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # +operator-builder:field:parent=metadata.name,replace="ocm-log-forwarder",type="string"
  name: ocm-log-forwarder-elastic
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
    resourceNames:
      # +operator-builder:field:name=backend.elasticsearch.secretRef,type=string,default="elastic-auth"
      - elastic-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # +operator-builder:field:parent=metadata.name,replace="ocm-log-forwarder",type="string"
  name: ocm-log-forwarder-ocm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # +operator-builder:field:parent=metadata.name,replace="ocm-log-forwarder",type="string"
  name: ocm-log-forwarder-ocm
subjects:
  - kind: ServiceAccount
    # +operator-builder:field:parent=metadata.name,type="string"
    name: ocm-log-forwarder
---
# +operator-builder:resource:field=backend.type,value=elasticsearch,include=true
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # +operator-builder:field:parent=metadata.name,replace="ocm-log-forwarder",type="string"
  name: ocm-log-forwarder-elastic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # +operator-builder:field:parent=metadata.name,replace="ocm-log-forwarder",type="string"
  name: ocm-log-forwarder-elastic
subjects:
  - kind: ServiceAccount
    # +operator-builder:field:parent=metadata.name,type="string"
    name: ocm-log-forwarder
