---
name: Release
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Generate Manifests
        shell: bash
        run: |
          make kustomize

          # generate controller manifests
          cd config/manager && ../../bin/kustomize edit set image controller=ghcr.io/scottd018/ocm-log-forwarder-operator:v{{ .Version }}
          ../../bin/kustomize build ../../config/default > ../../deploy.yaml

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTIONS_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist -f  ./.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
